FROM arm32v6/golang:1.11.0-alpine3.8

ADD build.rpi.cache.sh /
ADD Makefile /temp/

RUN apk update && apk add make git gcc libc-dev ca-certificates binutils-gold nodejs nodejs-npm && \
    chmod +x /build.rpi.cache.sh && \
    cd /temp && \
    GO111MODULE=on GOARM=6 GOARCH=arm  go mod init tmp/for/utils && \
    GO111MODULE=on GOARM=6 GOARCH=arm make utilities-build

CMD ["/build.rpi.cache.sh"]