FROM arm32v6/1.11.0-alpine3.8

ADD build.rpi.cache.sh .
ADD Makefile .

RUN apk update && apk add make git gcc libc-dev ca-certificates binutils-gold nodejs nodejs-npm && \
    chmod +x build.rpi.cache.sh && \
    make utilities-build

CMD ["./build.rpi.cache.sh"]