// Code generated by "enumer -type=SystemType -transform=kebab -trimprefix=Sys"; DO NOT EDIT.

package systems

import (
	"fmt"
)

const _SystemTypeName = "go-homeloggerbusdevicesecretconfigsecurity"

var _SystemTypeIndex = [...]uint8{0, 7, 13, 16, 22, 28, 34, 42}

func (i SystemType) String() string {
	if i < 0 || i >= SystemType(len(_SystemTypeIndex)-1) {
		return fmt.Sprintf("SystemType(%d)", i)
	}
	return _SystemTypeName[_SystemTypeIndex[i]:_SystemTypeIndex[i+1]]
}

var _SystemTypeValues = []SystemType{0, 1, 2, 3, 4, 5, 6}

var _SystemTypeNameToValueMap = map[string]SystemType{
	_SystemTypeName[0:7]:   0,
	_SystemTypeName[7:13]:  1,
	_SystemTypeName[13:16]: 2,
	_SystemTypeName[16:22]: 3,
	_SystemTypeName[22:28]: 4,
	_SystemTypeName[28:34]: 5,
	_SystemTypeName[34:42]: 6,
}

// SystemTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SystemTypeString(s string) (SystemType, error) {
	if val, ok := _SystemTypeNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to SystemType values", s)
}

// SystemTypeValues returns all values of the enum
func SystemTypeValues() []SystemType {
	return _SystemTypeValues
}

// IsASystemType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i SystemType) IsASystemType() bool {
	for _, v := range _SystemTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
